export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGUER_START = 'PURCHASE_BURGUER_START';
export const PURCHASE_BURGUER_SUCCESS = 'PURCHASE_BURGUER_SUCCESS';
export const PURCHASE_BURGUER_FAIL = 'PURCHASE_BURGUER_FAIL';
